import { isAxiosError } from "axios"
import  api  from '../config/axios'
import type { User } from '../types'
import type { ProfileForm } from '../types'

export async function getUser(){
    try {
        const { data } = await api<User>('/user', {
        })
        return data
    } catch (error) {
        if(isAxiosError(error) && error.response){
            throw new Error(error.response.data.error)
        }
    }
}

export async function updateProfile(formData: ProfileForm){
    try {
        const { data } = await api.patch<string>('/user', formData)
        return data
    } catch (error) {
        if(isAxiosError(error) && error.response){
            throw new Error(error.response.data.error)
        }
    }
}